### ISSUE TITLE
Cross shopping module

### ISSUE THREAD

**Issue by mvanwyk** [Data-Simply/pyretailscience#36]
![image](https://github.com/Data-Simply/pyretailscience/assets/2493311/adadb880-760e-44c7-a96f-117ae11a7e3a)

**TODO:**
Plotting
- [x] Optionally allow the user to select the 2-3 groups to plot
- [x] Allow for plotting based on any column and aggregation function

Other
- [ ] LinkedIn Post w/Carousel
- [x] Documentation page

**Comment by mvanwyk** [comment]
Done!
