### ISSUE TITLE
Add a cohort plot as a standard plot

### ISSUE THREAD

**Issue by mvanwyk** [Data-Simply/pyretailscience#37]
Add a cohort style plot with pandas tables

![image](https://github.com/Data-Simply/pyretailscience/assets/2493311/92e7fc93-2bbe-4b60-a573-fb27746df1c7)

**TODO**
- [ ] Display results in percent change from the first value or absolute values
- [ ] Use standard fonts, size, colors etc
- [ ] Allow for an optional title and source text
- [ ] Bonus: Allow for saving the plot as a png using this library https://github.com/dexplo/dataframe_image
- [ ] LinkedIn Post w/Carousel
- [ ] Documentation page
