### ISSUE TITLE
Product Association Module

### ISSUE THREAD

**Issue by mvanwyk** [Data-Simply/pyretailscience#47]
Allow for the discovery of frequently bought together items and categories.

**TODO:**
Identifying combinations
- [ ] Find combinations of 2-3 products/categories/etc that are bought often together. 
   - Display as a table with relevant KPIs 
- [ ] Allow for sorting by raw counts, uplift using apriori
- [ ] Allow for a min occurrence cut-off

Other
- [ ] LinkedIn Post w/Carousel
- [ ] Documentation page
