### ISSUE TITLE
Standard Line Plot

### ISSUE THREAD

**Issue by mvanwyk** [Data-Simply/pyretailscience#76]
**TODO**
- [ ] Create a standard line plot function and place it in a plots folder
- [ ] If there is an opportunity to make the code DRYer, standardize functionality
- [ ] If there is an opportunity to standardize wording between graphs and plots, use "plot"
- [ ] Documentation in the analysis modules page
