### ISSUE TITLE
Standard histogram plot

### ISSUE THREAD

**Issue by mvanwyk** [Data-Simply/pyretailscience#77]
**TODO**
- [ ] Create a standard histogram plot function and place it in a plots folder
- [ ] If there is an opportunity to make the code DRYer, standardize functionality
- [ ] If there is an opportunity to standardize wording between graphs and plots, use "plot"
- [ ] Update the documentation in the analysis modules page
