### ISSUE TITLE
Standard Bar Plot

### ISSUE THREAD

**Issue by mvanwyk** [Data-Simply/pyretailscience#78]
**TODO**
- [ ] Create a standard bar plot function and place it in a plots folder
- [ ] If there is an opportunity to make the code DRYer, standardize functionality
- [ ] If there is an opportunity to standardize wording between graphs and plots, use "plot"
- [ ] Update the documentation in the analysis modules page
